<template>
  <div>
    KavadsaKavKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsaKavadsav
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    adsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    KavadsaKavadsaKavadsaKavadsaKavadsa
    v
    KavadsaKavadsaKavadsaKavadsaKavadsa
  </div>
</template>

<script>
export default {
  name: 'SiteHome',
  // tu môže byť JavaScript špecifický pre Home.vue
}
</script>
